### ISSUE TITLE
Bot didn't send reply to messages

### ISSUE THREAD

**Issue by flupine** [Bjornskjald/miscord#101]
## Expected Behavior
![Expected](https://github.com/Bjornskjald/miscord/raw/gh-pages/img/screenshot.png)

## Actual Behavior
![Discord](https://i.imgur.com/XZgeoIG.png)
![Messenger](https://i.imgur.com/ZGRjxV9.png)

## Steps to Reproduce the Problem

  1. Receive message from messenger
  2. Reply to the message with discord
  3. The bot didn't send the text to messenger

## Specifications

  - Platform: Linux (ArchLinux)
  - Version (can be found in package.json): 2.5.0
  - Node.js version (`node -v`): 9.3.0

**Comment by flupine** [comment]
EDIT : I tried with an older version of miscrod (from commit: 46432528ec2773f3d176879e33216326b3063d43) and it works.

**Comment by JayTurnr** [comment]
I'm on c6ddc96e554ff409a025838e8d90371165453fe2 and I have this issue.

**Comment by flupine** [comment]
@JayTurnr Yes i have tested with c6ddc96e554ff409a025838e8d90371165453fe2 and effectively i have the same problem

**Comment by Bjornskjald** [comment]
I'll see what changes were made since https://github.com/Bjornskjald/miscord/commit/46432528ec2773f3d176879e33216326b3063d43 and I'll try to fix it.

**Comment by Bjornskjald** [comment]
@flupine @JayTurnr Could you test 2.5.1 from dev branch?

**Comment by flupine** [comment]
@Bjornskjald ok i will try

**Comment by flupine** [comment]
@Bjornskjald  now it work with the 2.5.1 from dev branch :100:

**Comment by flupine** [comment]
@Bjornskjald now i have sometimes this error : 
```
(node:1757) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
    at item.request.gen.end (/home/flupine/Documents/BOTS/miscord/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/flupine/Documents/BOTS/miscord/node_modules/snekfetch/src/index.js:213:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:1757) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1757) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Bjornskjald** [comment]
@fI also have this, it's because sometimes Discord loses track of the original message.  
Can you create a different issue?

**Comment by flupine** [comment]
@Bjornskjald Yes sure, thanks for your great work !
