### ISSUE TITLE
Messenger to Discord stopped working after running a while

### ISSUE THREAD

**Issue by simeonlg** [Bjornskjald/miscord#132]
Two nights in a row the Messenger to Discord bridge has stopped working, while the Discord to Messenger is working just fine. I pulled your most recent update yesterday and followed up with npm install. 

Error log:
```
info login Launching Miscord v2.6.10
info login Logging in...
info login Log level: info
info updateNotifier Checking for updates...
New version 2.6.9 available! 
Changelog:
- Added switch to disable auto-renaming channels
info login Logging in to Discord...
info login Logged in to Discord
info login Got Discord channels list
info login Logging in to Facebook...
info login Logged in
(node:1340) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
    at item.request.gen.end (/home/pi/miscord/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
    at then (/home/pi/miscord/node_modules/snekfetch/src/index.js:213:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:1340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1340) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ERR! listen Error: getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443
ERR! listen     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
ERR! listen  { Error: getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443
ERR! listen     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
ERR! listen   cause: 
ERR! listen    { Error: getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443
ERR! listen     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
ERR! listen      message: 'getaddrinfo ENOTFOUND 0-edge-chat.facebook.com 0-edge-chat.facebook.com:443',
ERR! listen      errno: 'ENOTFOUND',
ERR! listen      code: 'ENOTFOUND',
ERR! listen      syscall: 'getaddrinfo',
ERR! listen      hostname: '0-edge-chat.facebook.com',
ERR! listen      host: '0-edge-chat.facebook.com',
ERR! listen      port: 443 },
ERR! listen   isOperational: true,
ERR! listen   errno: 'ENOTFOUND',
ERR! listen   code: 'ENOTFOUND',
ERR! listen   syscall: 'getaddrinfo',
ERR! listen   hostname: '0-edge-chat.facebook.com',
ERR! listen   host: '0-edge-chat.facebook.com',
ERR! listen   port: 443 }
Unhandled rejection TypeError: Cannot read property 'threadID' of undefined
    at module.exports.opts (/home/pi/miscord/lib/listeners/facebook.js:19:48)
    at config.facebook.client.listen (/home/pi/miscord/index.js:12:51)
    at /home/pi/miscord/node_modules/facebook-chat-api/src/listen.js:443:11
    at tryCatcher (/home/pi/miscord/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/pi/miscord/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/pi/miscord/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/pi/miscord/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/pi/miscord/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/pi/miscord/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/miscord/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

EDIT: It happened again now after running for about 2 hours. A message from messenger to discord went through at 11:05, but the next message from messenger to discord at 11:20 did not. Messages from discord to messenger are still operational

**Comment by Bjornskjald** [comment]
It seems like your internet connection is unstable

**Comment by Bjornskjald** [comment]
But the `Unknown Message` error seems weird, can you change log level to `silly`?

**Comment by simeonlg** [comment]
It happened again with log set to silly now
[putty.log](https://github.com/Bjornskjald/miscord/files/1844495/putty.log)

**Comment by Bjornskjald** [comment]
Damn, 12MB of logs? But again, seems like unstable internet connection.

**Comment by simeonlg** [comment]
I just took the log straight from putty after running for 9 hours.

The connection does seem to be the issue, currently using a wifi dongle as I am out of free spots in my router, will get that sorted and report back if it happens again with a wired connection.
