### ISSUE TITLE
Unhandled Error?

### ISSUE THREAD

**Issue by ShinNinth** [Bjornskjald/miscord#197]
_If you have a question, ask on the [Miscord Support server](https://discord.gg/DkmTvVz) instead_  
## Expected Behavior
Continued Operation

## Actual Behavior
App closes out throwing the following message:

events.js:188
      throw err;
      ^

Error: Unhandled "error" event. ([object Object])
    at Client.emit (events.js:186:19)
    at WebSocketConnection.onError (C:\Users\dedicated\AppData\Roaming\npm\node_modules\miscord\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:374:17)
    at WebSocket.onError (C:\Users\dedicated\AppData\Roaming\npm\node_modules\miscord\node_modules\ws\lib\event-target.js:128:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at _receiver.cleanup (C:\Users\dedicated\AppData\Roaming\npm\node_modules\miscord\node_modules\ws\lib\websocket.js:211:14)
    at Receiver.cleanup (C:\Users\dedicated\AppData\Roaming\npm\node_modules\miscord\node_modules\ws\lib\receiver.js:557:13)
    at WebSocket.finalize (C:\Users\dedicated\AppData\Roaming\npm\node_modules\miscord\node_modules\ws\lib\websocket.js:206:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

## Steps to Reproduce the Problem

  1.Havent been able to narrow down the cause yet it always happens while im at work and cant watch it.  Also havent been able to force it to replicate yet.
  1.
  1.

## Specifications

  - Platform: Windows
  - Version (`miscord -v`):3.0.14
  - Node.js version (`node -v`):8.11.1

**Comment by RobCraftNet** [comment]
too me

**Comment by Bjornskjald** [comment]
```
at WebSocketConnection.onError
```
Basically, it means an unknown connection error.

**Comment by ShinNinth** [comment]
Is it possible to maybe gracefully reconnect from this error after a certain amount of time?

**Comment by Bjornskjald** [comment]
The problem is, that error is unhandled, and I don't know where it occurs...

**Comment by Bjornskjald** [comment]
Uh, okay... all I was meant to do was add an 'event' listener for Discord client...
