### ISSUE TITLE
Unable to npm start to due to bin/index.js

### ISSUE THREAD

**Issue by clhleung** [Bjornskjald/miscord#225]
In the past, I had success running Miscord on an Amazon Linux EC2 Instance, and decided to update to the latest build. I installed the LTS version for Node JS 8.11, and have npm installed as seen in the log file. After  I followed the local install instructions (cloned repo, npm install, configured config.json), I used npm start and got errors. I checked the log files and this is what it gave me, which left me confused since I do have index.js within the bin directory. 
```
[root@ip-172-31-44-33 _logs]# cat 2018-05-22T21_38_12_957Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v8.11.2/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v8.11.2/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--config',
1 verbose cli   '/home/ec2-user/miscord/config.json' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle miscord@3.3.1~prestart: miscord@3.3.1
6 info lifecycle miscord@3.3.1~start: miscord@3.3.1
7 verbose lifecycle miscord@3.3.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle miscord@3.3.1~start: PATH: /root/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ec2-user/miscord/node_modules/.bin:/root/.nvm/versions/node/v8.11.2/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin
9 verbose lifecycle miscord@3.3.1~start: CWD: /home/ec2-user/miscord
10 silly lifecycle miscord@3.3.1~start: Args: [ '-c',
10 silly lifecycle   'node bin/index.js "--config" "/home/ec2-user/miscord/config.json"' ]
11 silly lifecycle miscord@3.3.1~start: Returned: code: 1  signal: null
12 info lifecycle miscord@3.3.1~start: Failed to exec start script
13 verbose stack Error: miscord@3.3.1 start: `node bin/index.js "--config" "/home/ec2-user/miscord/config.json"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid miscord@3.3.1
15 verbose cwd /home/ec2-user/miscord
16 verbose Linux 4.14.26-46.32.amzn1.x86_64
17 verbose argv "/root/.nvm/versions/node/v8.11.2/bin/node" "/root/.nvm/versions/node/v8.11.2/bin/npm" "start" "--" "--config" "/home/ec2-user/miscord/config.json"
18 verbose node v8.11.2
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error miscord@3.3.1 start: `node bin/index.js "--config" "/home/ec2-user/miscord/config.json"`
22 error Exit status 1
23 error Failed at the miscord@3.3.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Bjornskjald** [comment]
Didn't you read what it said in the console?

**Comment by clhleung** [comment]
This is what the console gave me after I typed npm start, where it logs into Discord and then gives off an error with bin.

```
> miscord@3.3.1 start /home/ec2-user/miscord
> node bin/index.js

info getConfig Using config at /root/.config/Miscord/config.json
info login Launching Miscord v3.3.1
info login Logging in...
info login Log level: info
info updateNotifier Checking for updates...
info login Logging in to Discord...
info login Logged in to Discord
ERR! error bin

WARN Logs from NPM are unnecessary and don't give much information.
WARN Miscord logs folder:
WARN /root/.config/Miscord/logs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! miscord@3.3.1 start: `node bin/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the miscord@3.3.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-22T21_56_40_445Z-debug.log
[root@ip-172-31-44-33 miscord]# node bin/index.js
info getConfig Using config at /root/.config/Miscord/config.json
info login Launching Miscord v3.3.1
info login Logging in...
info login Log level: info
info updateNotifier Checking for updates...
info login Logging in to Discord...
info login Logged in to Discord
ERR! error bin

WARN Logs from NPM are unnecessary and don't give much information.
WARN Miscord logs folder:
WARN /root/.config/Miscord/logs
```

**Comment by Bjornskjald** [comment]
Ok, my fault, the error wasn't showing up correctly. Can you update to 3.3.2?

**Comment by clhleung** [comment]
I'm not sure whether Docker integration was fixed but this was the Dockerfile I used when I cloned both the git repo and did an npm install on miscord, which I got working on an Amazon Ec2 instance running Docker. Originally I got it working with just using npm start, but that required me to keep a connection to the Amazon Ec2 instance running at all times. I wanted to run it with Docker, since that allowed me to run it without keeping that continuous connection, and after modifying the Dockerfile this is what I got as a solution (originally had problems with the classpath issue not finding config.json). Of course it may sound inefficient to clone the repo and do an npm install but I just wanted to post out a solution to those that do.  

```
FROM node:alpine
LABEL maintainer="Bjornskjald <github@bjorn.ml>"

RUN npm install --only=production -g miscord

ADD . / my/



CMD (cd my/;miscord -c "/my/config.json";)
```

**Comment by Bjornskjald** [comment]
But... you can use your config file from Docker volume which generates by default at /config.
Also, there is a prebuilt image on Docker Hub at bjornskjald/miscord
